### ISSUE TITLE
howto increase openresty gateway time-out ?

### ISSUE THREAD

**Issue by Cyrille37** [Valian/docker-nginx-auto-ssl#30]
Hello
Thanks a lot for your really great docker image.

I could not find how to increase openresty gateway time-out ? When used with small VM I got error "504 Gateway Time-out, openresty/1.15.8.1"

Cheers.

**Comment by Valian** [comment]
Hi @Cyrille37! This is a standard nginx option called 'proxy_read_timeout' and is not really related to this project, because timeout occurs after generation of certificate. In readme you can find instructions how to configure your endpoint. 

More about nginx timeouts here http://nginx.org/en/docs/http/ngx_http_proxy_module.html

**Comment by Cyrille37** [comment]
Hello
I thought that was the openresty gateway, not nginx sub-sites.
I'll deeper investigate.
Thanks & cheers.
