### ISSUE TITLE
Adding multiple domains?

### ISSUE THREAD

**Issue by galaczi** [Valian/docker-nginx-auto-ssl#46]
How would you go about adding multiple domains? 

I have tried with:

ALLOWED_DOMAINS: "(example.com)|(www.example.com)|(example.net)"

And it doesn't work.

**Comment by galaczi** [comment]
Nevermind, it's just a comma-separated list without spaces.

**Comment by galaczi** [comment]
Reopening. Adding a comma-separated list makes nginx pick up those domains, but certificates are not created.

**Comment by Valian** [comment]
Hi @galaczi. ALLOWED_DOMAINS has nothing to do with your nginx routing configuration, this setting is only used to verify if OpenResty should try to generate certificate for given domain or not. Otherwise, it would be very easy to force generation of certificates for domains you don't own by faking HOST header, more [here](https://github.com/auto-ssl/lua-resty-auto-ssl#allow_domain). 

About the proper way to define multiple domains, everything is in README. 
> ALLOWED_DOMAINS: Regex pattern of allowed domains. Internally, we're using [ngx.re.match](https://github.com/openresty/lua-nginx-module#ngxrematch). By default, we accept all domains.

You have to define domains like this: `ALLOWED_DOMAINS="(example1.com|example2.com)"`
