### ISSUE TITLE
Several containers of this image across nodes

### ISSUE THREAD

**Issue by PabloZaiden** [Valian/docker-nginx-auto-ssl#6]
What would be a good way to use this, while having several containers on different nodes in a cluster of the same image?

**Comment by Valian** [comment]
Hi @PabloZaiden, I'm not sure if I understand your problem correctly. You have multiple servers, some containers on each of them, and you want to make load balancing and SSL termination using my image?

If yes, then you have to remember to deploy `nginx-auto-ssl` only on one node, define properly upstream proxy (http://nginx.org/en/docs/http/ngx_http_upstream_module.html), do rest as described in the readme and you should be ready to go :+1:

**Comment by PabloZaiden** [comment]
Thanks @Valian, I'm already doing that. The thing I was thinking is a better way to have high availability, considering that the node where the container handling the SSL termination could go down.

**Comment by Valian** [comment]
Sadly I'm not aware of any Open Source solution that would handle this case easily. When you are doing loadbalancing in front of nginx containers, there is no guarantee which one will answer to LE challenge, and it will most likely fail. Things that are coming to my mind:

1. Terminate SSL on a loadbalancer level, but you probably will need to generate cert on your own somehow
2. Use network volume for certificates, generate them using DNS challenges. But sadly it won't be as easy. 
3. If you are using Kubernetes, you may check this  https://itnext.io/automated-tls-with-cert-manager-and-letsencrypt-for-kubernetes-7daaa5e0cae4

Personally, when HA is not required I'm using this image on just one node, otherwise, I'm baking certs into custom nginx image and I'm updating all of them using script every two months. Hope this will help you!

**Comment by PabloZaiden** [comment]
Thanks! I'm doing pretty much the same things. Was hoping someone already did something as out-of-the-box as this image, but with HA.

Thanks again!
